### PR TITLE
Fix conditional useQuery

### LINKED ISSUE #238: Some stories don't work anymore
Didn't check out the cause yet, but already fails in current next

- Table Besides Form
- Table Besides Form Selection Hooks

### PR DESCRIPTION
**Pull request by fraxachun**
- skip only works when query is given
- useQuery must be executed unconditionally, hence own component

Closes #238

### CODE REVIEW

File: packages/react-admin/src/Selected.tsx [hunk 1]
```diff
@@ -21,41 +21,45 @@ const ProgressContainer = styled.div`
     justify-content: center;
 `;
 
+const SelectEdit = (props: IProps) => {
+    console.log(props.query);
```
Comment (rabengraph) [inline packages/react-admin/src/Selected.tsx:25]:
```suggestion
```

File: packages/react-admin/src/Selected.tsx [hunk 2]
```diff
@@ -21,41 +21,45 @@ const ProgressContainer = styled.div`
...
+};
+
 export function Selected(props: IProps) {
-    const ErrorComponent = props.components?.error;
     let row;
     if (props.rows) {
         row = props.rows.find((i) => String(i.id) === String(props.selectedId)); // compare as strings as selectedId might come from url
     }
 
-    const queryResult = useQuery(props.query!, { variables: { id: props.selectedId }, skip: props.query === undefined });
```
Comment (rabengraph) [inline packages/react-admin/src/Selected.tsx:31]: The query is not executed conditionally. I think the the problem was that an if-condition is defined (line 27) before a hook is defined (line 31). So swapping the 2 statements should fix any hook-lint warnings.

Or do you mean with "executed conditionally" the passed "skip"-option?

Generally a good way to handle conditional queries with apollo is using `useLazyQuery` instead of `useQuery`.
https://www.apollographql.com/docs/react/data/queries/#executing-queries-manually

**Review by rabengraph — APPROVED** [review]

**Review by nsams — APPROVED** [review]
:+1: easier to understand now what is happening

**Review by kaufmo — APPROVED** [review]

File: packages/react-admin/src/Selected.tsx (hunk 2 above)
Comment (fraxachun) [reply packages/react-admin/src/Selected.tsx:31]: With "conditionally" I meant the skip statement. useQuery does not accept an empty query, even though the query would be skipped due to the skip-property. Maybe the change of the behavior was introduced with the Apollo-update, I didn't double-check this though.
